baseURL: "https://marimo-kd.github.io/"
languageCode: "ja-jp"
title: "marimo's blog"
theme: "PaperMod"

params:
  defaultTheme: light
  homeInfoParams:
    Title: marimo's blog
    Content: marimoのブログです。いろいろある予定です。

  socialIcons:
    - name: twitter
      url: "https://twitter.com/MMARIMO0o"
    - name: github
      url: "https://github.com/marimo-KD"

  ShowShareButtons: false
  ShowReadintTime: true
  ShowToc: true
  enableInlineShortcodes: true

menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
